(() => {
  const SUPABASE_URL = 'https://pzhfybtoyfttftgcrcxk.supabase.co';
  const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_yGiDH_M0fUZglk40fCk7cQ_kkL1XKzj';
  const READ_KEY = 'investition-news-read-v26';
  const $ = (q, el = document) => el.querySelector(q);
  const $$ = (q, el = document) => [...el.querySelectorAll(q)];
  const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  const safeUrl = value => { try { const u = new URL(String(value)); return ['http:','https:'].includes(u.protocol) ? u.href : ''; } catch { return ''; } };
  const sb = window.supabase?.createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, { auth:{persistSession:false,autoRefreshToken:true,detectSessionInUrl:true} });

  const els = {
    tradingPage:$('#tradingPage'), decisionPage:$('#decisionPage'), analyticsPage:$('#analyticsPage'), newsPage:$('#newsPage'), navTrading:$('#navTradingBtn'), navDecision:$('#navDecisionBtn'), navAnalytics:$('#navAnalyticsBtn'), navNews:$('#navNewsBtn'),
    list:$('#newsList'), detail:$('#newsDetail'), detailCard:$('#newsDetailCard'), count:$('#newsCountChip'), lastUpdated:$('#newsLastUpdated'),
    search:$('#newsSearchInput'), scope:$('#newsScopeFilter'), topic:$('#newsTopicFilter'), impact:$('#newsImpactFilter'), read:$('#newsReadFilter'),
    sync:$('#newsSyncBtn'), importBtn:$('#newsImportBtn'), importFile:$('#newsImportFile'), status:$('#newsStatus'), markAll:$('#markAllReadBtn'),
    cloudHealth:$('#newsCloudHealth'), tableHealth:$('#newsTableHealth'), functionHealth:$('#newsFunctionHealth'), providerHealth:$('#newsProviderHealth'),
    priorityStrip:$('#newsPriorityStrip'), portfolioCount:$('#portfolioNewsCount'), watchlistCount:$('#watchlistNewsCount'), sectorCount:$('#sectorNewsCount'), marketCount:$('#marketNewsCount')
  };
  if (!els.newsPage) return;

  let items = [], selectedId = null, session = null, realtimeChannel = null;
  let readIds = loadReadIds();
  let portfolio = [], watchlist = [];

  function loadReadIds(){ try { const x=JSON.parse(localStorage.getItem(READ_KEY)||'[]'); return new Set(Array.isArray(x)?x:[]); } catch { return new Set(); } }
  function saveReadIds(){ try { localStorage.setItem(READ_KEY,JSON.stringify([...readIds])); } catch {} }
  function normalizeText(v){ return String(v||'').normalize('NFKD').toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9+/.:-]+/g,' ').replace(/\s+/g,' ').trim(); }
  function symbolTokens(v){ const x=String(v||'').toUpperCase().replace(/\s+/g,''); if(!x)return[]; const s=new Set([x]); if(x.includes(':'))s.add(x.split(':').pop()); if(x.includes('.'))s.add(x.split('.')[0]); return [...s].filter(Boolean); }
  function normalize(n){ return { id:n.id, external_id:n.external_id, published_at:n.published_at||new Date().toISOString(), topic:n.topic||'Sonstiges', title:n.title||'Ohne Titel', summary:n.summary||'', content:n.content||n.summary||'', source_url:n.source_url||'', source_name:n.source_name||'News', symbols:Array.isArray(n.symbols)?n.symbols:[], tags:Array.isArray(n.tags)?n.tags:[], sentiment:n.sentiment??null, impact:String(n.impact||'mittel').toLowerCase(), priced_in:n.priced_in||'Noch nicht bewertet', analyst_view:n.analyst_view||'Noch nicht bewertet', market_impact:n.market_impact||'' }; }
  function dateTime(v){ const d=new Date(v); return Number.isNaN(d.getTime())?String(v||'—'):new Intl.DateTimeFormat('de-DE',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Berlin'}).format(d); }
  function setStatus(text,type=''){ els.status.textContent=text; els.status.className=`news-status ${type}`; }
  function setHealth(el,value,type=''){ if(!el)return; el.className=`news-health-item ${type}`; const t=$('.value',el); if(t)t.textContent=value; }
  function impactClass(v){ return v==='hoch'?'bad':v==='niedrig'?'neutral':'warn'; }
  function relevanceScore(n,scope){ let score=scope==='portfolio'?5:scope==='watchlist'?4:scope==='sector'?3:2; if(n.impact==='hoch')score=Math.min(5,score+1); if(Math.abs(Number(n.sentiment||0))>.55)score=Math.min(5,score+1); return score; }
  function referenceAliases(ref){ const values=[ref.name,ref.symbol,ref.market_symbol,ref.isin,ref.wkn].filter(Boolean); const aliases=new Set(); for(const v of values){ const x=normalizeText(v); if(x.length>=3)aliases.add(x); for(const token of x.split(/[\s.:/]+/)) if(token.length>=4)aliases.add(token); } return [...aliases]; }
  function matchesReference(n,ref){ const wanted=new Set([...symbolTokens(ref.symbol),...symbolTokens(ref.market_symbol)]); if(n.symbols.some(s=>symbolTokens(s).some(t=>wanted.has(t))))return true; const hay=normalizeText(`${n.title} ${n.summary} ${n.content}`); return referenceAliases(ref).some(a=>hay.includes(a)); }
  function classify(n){ const held=portfolio.filter(p=>matchesReference(n,p)); if(held.length)return {scope:'portfolio',refs:held}; const watched=watchlist.filter(p=>matchesReference(n,p)); if(watched.length)return {scope:'watchlist',refs:watched}; if(['KI','Halbleiter','Energie','Unternehmen'].includes(n.topic))return {scope:'sector',refs:[]}; return {scope:'market',refs:[]}; }
  function enriched(){ return items.map(n=>{ const c=classify(n); return {...n,scope:c.scope,refs:c.refs,relevance:relevanceScore(n,c.scope)}; }); }
  function filtered(){ const q=normalizeText(els.search.value); return enriched().sort((a,b)=>b.relevance-a.relevance||String(b.published_at).localeCompare(String(a.published_at))).filter(n=>{ const hay=normalizeText([n.topic,n.title,n.summary,n.content,n.symbols.join(' '),n.tags.join(' '),n.refs.map(r=>r.name).join(' ')].join(' ')); if(q&&!hay.includes(q))return false; if(els.scope.value&&n.scope!==els.scope.value)return false; if(els.topic.value&&n.topic!==els.topic.value)return false; if(els.impact.value&&n.impact!==els.impact.value)return false; const read=readIds.has(n.id); if(els.read.value==='read'&&!read)return false; if(els.read.value==='unread'&&read)return false; return true; }); }
  function updateCounts(){ const all=enriched(); const count=s=>all.filter(n=>n.scope===s).length; els.portfolioCount.textContent=count('portfolio'); els.watchlistCount.textContent=count('watchlist'); els.sectorCount.textContent=count('sector'); els.marketCount.textContent=count('market'); $$('[data-scope]',els.priorityStrip).forEach(b=>b.classList.toggle('active',els.scope.value===b.dataset.scope)); }
  function renderList(){ updateCounts(); const list=filtered(); els.count.textContent=`${list.length} ${list.length===1?'Eintrag':'Einträge'}`; if(!list.length){ els.list.innerHTML='<div class="news-empty">Keine Meldungen für den gewählten Filter. „Feed aktualisieren“ sucht zusätzlich gezielt nach Nachrichten zu Depotpositionen und Watchlist-Werten.</div>'; renderDetail(null); return; } if(!list.some(n=>n.id===selectedId))selectedId=list[0].id; els.list.innerHTML=list.map(n=>`<button class="news-item ${n.id===selectedId?'selected':''} ${readIds.has(n.id)?'':'unread'}" data-news-id="${escapeHtml(n.id)}"><div class="news-meta-row"><span class="news-scope ${n.scope}">${n.scope==='portfolio'?'Portfolio':n.scope==='watchlist'?'Watchlist':n.scope==='sector'?'Branche':'Markt'}</span><span class="news-time">${escapeHtml(dateTime(n.published_at))}</span></div><div class="news-title">${escapeHtml(n.title)}</div><div class="news-summary">${escapeHtml(n.summary||n.content)}</div><div class="news-tags"><span class="news-stars">${'★'.repeat(n.relevance)}${'☆'.repeat(5-n.relevance)}</span><span class="chip ${impactClass(n.impact)}">${escapeHtml(n.impact)}</span>${n.refs.slice(0,2).map(r=>`<span class="chip neutral">${escapeHtml(r.name)}</span>`).join('')}${n.symbols.slice(0,2).map(s=>`<span class="chip neutral">${escapeHtml(s)}</span>`).join('')}</div></button>`).join(''); $$('[data-news-id]',els.list).forEach(b=>b.onclick=()=>selectItem(b.dataset.newsId)); renderDetail(list.find(n=>n.id===selectedId)); }
  function renderDetail(n){ if(!n){ els.detail.innerHTML='<div class="news-empty">Wähle einen Eintrag aus der Liste.</div>'; return; } const source=safeUrl(n.source_url); const refs=n.refs||[]; const portfolioInfo=refs.length?refs.map(r=>`<button type="button" class="btn small news-analysis-link" data-analysis-symbol="${escapeHtml(r.symbol||r.market_symbol||'')}"><span>${escapeHtml(r.name)}</span><span>Analyse öffnen →</span></button>`).join(' '):'Keine direkte Position zugeordnet'; const sentiment=Number(n.sentiment); const direction=Number.isFinite(sentiment)?(sentiment>.15?'positiv':sentiment<-.15?'negativ':'neutral'):'nicht bewertet'; els.detail.innerHTML=`<div class="news-scope ${n.scope}">${n.scope==='portfolio'?'Portfolio-News':n.scope==='watchlist'?'Watchlist-News':n.scope==='sector'?'Branchen-News':'Markt-News'}</div><h2>${escapeHtml(n.title)}</h2><div class="news-detail-meta"><span>${escapeHtml(dateTime(n.published_at))}</span><span>•</span><span>${escapeHtml(n.source_name)}</span><span class="news-stars">${'★'.repeat(n.relevance)}${'☆'.repeat(5-n.relevance)}</span><span class="chip ${impactClass(n.impact)}">Relevanz ${escapeHtml(n.impact)}</span></div>${n.summary?`<div class="notice"><div>◆</div><div><strong>Warum relevant:</strong> ${escapeHtml(n.summary)}</div></div>`:''}<div class="news-analysis-grid"><div class="news-analysis-box"><div class="label">Auswirkung / Sentiment</div><div class="value">${escapeHtml(n.market_impact||direction)}</div></div><div class="news-analysis-box"><div class="label">Bereits eingepreist?</div><div class="value">${escapeHtml(n.priced_in)}</div></div><div class="news-analysis-box"><div class="label">Analystenbild</div><div class="value">${escapeHtml(n.analyst_view)}</div></div></div><div class="news-detail-content">${escapeHtml(n.content||n.summary||'Kein Volltext verfügbar.')}</div><div class="news-analysis-box" style="margin-top:16px"><div class="label">Betroffene Positionen / Analysen</div><div class="value">${portfolioInfo}</div></div>${source?`<a class="btn news-source-link" href="${escapeHtml(source)}" target="_blank" rel="noopener noreferrer">Originalquelle öffnen ↗</a>`:''}`; $$('[data-analysis-symbol]',els.detail).forEach(b=>b.onclick=()=>openLinkedAnalysis(b.dataset.analysisSymbol||'')); }
  function openLinkedAnalysis(symbol){ const d=window.InvestitionDashboard; const result=d?.openAnalysisBySymbol?.(symbol); if(!result?.ok){ setStatus(`Für ${symbol||'dieses Wertpapier'} wurde keine verknüpfte Analyse gefunden.`,'bad'); return; } showPage('trading'); setStatus(`Analyse ${result.name} geöffnet.`,'good'); }
  function selectItem(id){ selectedId=id; readIds.add(id); saveReadIds(); renderList(); if(matchMedia('(max-width:980px)').matches)els.detailCard.scrollIntoView({behavior:'smooth',block:'start'}); }
  function showPage(name){ const page=['decision','trading','analytics','news'].includes(name)?name:'decision'; els.tradingPage.hidden=page!=='trading'; if(els.decisionPage)els.decisionPage.hidden=page!=='decision'; if(els.analyticsPage)els.analyticsPage.hidden=page!=='analytics'; els.newsPage.hidden=page!=='news'; els.navTrading?.classList.toggle('active',page==='trading'); els.navDecision?.classList.toggle('active',page==='decision'); els.navAnalytics?.classList.toggle('active',page==='analytics'); els.navNews?.classList.toggle('active',page==='news'); history.replaceState(null,'',`#${page}`); if(page==='news')renderList(); if(page==='decision')window.dispatchEvent(new CustomEvent('investition:decision-visible')); if(page==='analytics')window.dispatchEvent(new CustomEvent('investition:analytics-visible')); }
  function pageFromHash(){ const v=String(location.hash||'').replace('#',''); return ['decision','trading','analytics','news'].includes(v)?v:'decision'; }
  async function loadReferences(){ if(!sb||!session)return; const [p,d]=await Promise.all([sb.from('trade_plans').select('id,name,symbol,market_symbol,status,type,wkn,isin').order('updated_at',{ascending:false}),sb.from('depot_positions').select('id,trade_id,name,symbol,instrument_type,is_open').eq('is_open',true)]); const plans=p.data||[]; const planById=new Map(plans.map(x=>[x.id,x])); portfolio=(d.data||[]).map(x=>({...planById.get(x.trade_id),...x,name:x.name||planById.get(x.trade_id)?.name||'Depotposition',market_symbol:planById.get(x.trade_id)?.market_symbol||null,wkn:planById.get(x.trade_id)?.wkn||null,isin:planById.get(x.trade_id)?.isin||null})); const heldTradeIds=new Set(portfolio.map(x=>x.trade_id).filter(Boolean)); watchlist=plans.filter(x=>!heldTradeIds.has(x.id)&&!['Geschlossen','Verworfen'].includes(x.status)); }
  async function loadCloudNews(){ if(!sb||!session){ setHealth(els.cloudHealth,'nicht angemeldet','warn'); return; } setHealth(els.cloudHealth,session.user.email||'angemeldet','good'); setStatus('Portfolio- und Markt-News werden geladen …'); await loadReferences(); const {data,error}=await sb.from('market_news').select('*').eq('is_published',true).order('published_at',{ascending:false}).limit(500); if(error){ setHealth(els.tableHealth,error.message,'bad'); setStatus(`News konnten nicht geladen werden: ${error.message}`,'bad'); return; } items=(data||[]).map(normalize); selectedId=items.some(n=>n.id===selectedId)?selectedId:items[0]?.id||null; setHealth(els.tableHealth,`erreichbar · ${items.length} Zeilen`,items.length?'good':'warn'); els.lastUpdated.textContent=items[0]?`Neueste Meldung: ${dateTime(items[0].published_at)}`:'Noch keine Meldungen'; setStatus(`${items.length} Meldungen geladen · ${portfolio.length} Depotpositionen · ${watchlist.length} Watchlist-Werte.`,'good'); renderList(); window.dispatchEvent(new CustomEvent('investition:news-changed',{detail:{count:items.length}})); }
  async function syncNews(){ if(!sb||!session){ setStatus('Bitte zuerst anmelden.','bad'); return; } els.sync.disabled=true; setHealth(els.functionHealth,'gezielte Suche läuft …','warn'); setStatus('Unternehmens-, Portfolio- und Branchen-News werden synchronisiert …'); const {data,error}=await sb.functions.invoke('sync-news',{body:{force:true,portfolio:true,relink:true}}); els.sync.disabled=false; if(error){ let detail=error.message||String(error); try{ if(error.context instanceof Response){ const body=await error.context.clone().json(); detail=body.error||detail; } }catch{} setHealth(els.functionHealth,detail,'bad'); setStatus(`Synchronisierung fehlgeschlagen: ${detail}`,'bad'); return; } setHealth(els.functionHealth,`erfolgreich · ${data?.inserted??0} gespeichert`,'good'); setHealth(els.providerHealth,data?.provider||'EODHD + RSS','good'); setStatus(`${data?.inserted??0} Meldungen gespeichert; ${data?.tracked_instruments??0} Wertpapiere gezielt geprüft.`,'good'); await loadCloudNews(); }
  async function importNews(file){ try{ const parsed=JSON.parse(await file.text()); const incoming=Array.isArray(parsed)?parsed:parsed.news; if(!Array.isArray(incoming))throw new Error('Kein gültiges News-Array.'); const rows=incoming.map(normalize).map(n=>({...n,is_published:true})); const {error}=await sb.from('market_news').upsert(rows,{onConflict:'external_id'}); if(error)throw error; setStatus(`${rows.length} Meldungen importiert.`,'good'); await loadCloudNews(); }catch(e){ setStatus(`Import fehlgeschlagen: ${e.message}`,'bad'); } }
  function subscribeRealtime(){ if(!sb||!session)return; if(realtimeChannel)sb.removeChannel(realtimeChannel); realtimeChannel=sb.channel('market-news-v26').on('postgres_changes',{event:'*',schema:'public',table:'market_news'},()=>loadCloudNews()).subscribe(); }
  async function initCloud(){ if(!sb){ setHealth(els.cloudHealth,'Supabase fehlt','bad'); return; } const {data}=await sb.auth.getSession(); session=data.session; if(session){ subscribeRealtime(); await loadCloudNews(); } sb.auth.onAuthStateChange((_e,s)=>{ session=s; setTimeout(()=>{ if(session){subscribeRealtime();loadCloudNews();} else {items=[];portfolio=[];watchlist=[];renderList();}},0); }); }

  els.navTrading.onclick=()=>showPage('trading'); if(els.navDecision)els.navDecision.onclick=()=>showPage('decision'); if(els.navAnalytics)els.navAnalytics.onclick=()=>showPage('analytics'); els.navNews.onclick=()=>showPage('news');
  [els.search,els.scope,els.topic,els.impact,els.read].forEach(el=>el?.addEventListener('input',renderList));
  $$('[data-scope]',els.priorityStrip).forEach(b=>b.onclick=()=>{ els.scope.value=els.scope.value===b.dataset.scope?'':b.dataset.scope; renderList(); });
  els.sync.onclick=syncNews; els.importBtn.onclick=()=>els.importFile.click(); els.importFile.onchange=async()=>{const f=els.importFile.files[0];if(f)await importNews(f);els.importFile.value='';}; els.markAll.onclick=()=>{items.forEach(n=>readIds.add(n.id));saveReadIds();renderList();};
  window.addEventListener('hashchange',()=>showPage(pageFromHash())); window.InvestitionNavigation=Object.assign(window.InvestitionNavigation||{},{showPage,getPage:pageFromHash}); window.InvestitionNews=Object.assign(window.InvestitionNews||{},{getItems:()=>enriched(),refresh:loadCloudNews,sync:syncNews});
  showPage(pageFromHash()); renderList(); initCloud();
})();
