-- Investition Dashboard V29.2 Hybrid
-- Kostenfreier RSS-News-Sync, sparsamer EODHD-Tagescache und Sync-Protokoll.
-- Idempotent: kann gefahrlos erneut ausgeführt werden.

do $$
begin
  if to_regclass('public.market_news') is null then
    raise exception
      'Tabelle public.market_news fehlt. Zuerst version26-news-schema.sql ausführen.';
  end if;
end
$$;

create table if not exists public.hybrid_market_cache (
  symbol text primary key,
  provider text not null,
  price_bars jsonb not null default '[]'::jsonb,
  fetched_at timestamptz,
  last_attempt_at timestamptz,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.hybrid_market_cache enable row level security;
revoke all on table public.hybrid_market_cache from anon, authenticated;
grant select, insert, update, delete on table public.hybrid_market_cache
  to service_role;

create table if not exists public.hybrid_api_usage (
  usage_date date primary key,
  eodhd_calls smallint not null default 0
    check (eodhd_calls between 0 and 20),
  updated_at timestamptz not null default now()
);

alter table public.hybrid_api_usage enable row level security;
revoke all on table public.hybrid_api_usage from anon, authenticated;
grant select, insert, update, delete on table public.hybrid_api_usage
  to service_role;

create or replace function public.reserve_hybrid_eodhd_calls(
  p_calls integer default 1,
  p_daily_limit integer default 6
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_usage_date date := (now() at time zone 'UTC')::date;
  v_new_total integer;
  v_calls integer := greatest(1, least(coalesce(p_calls, 1), 20));
  v_limit integer := greatest(0, least(coalesce(p_daily_limit, 6), 20));
begin
  if v_limit = 0 or v_calls > v_limit then
    return false;
  end if;

  insert into public.hybrid_api_usage(
    usage_date,
    eodhd_calls,
    updated_at
  )
  values (
    v_usage_date,
    v_calls,
    now()
  )
  on conflict (usage_date) do update
    set
      eodhd_calls = public.hybrid_api_usage.eodhd_calls + excluded.eodhd_calls,
      updated_at = now()
    where public.hybrid_api_usage.eodhd_calls + excluded.eodhd_calls <= v_limit
  returning eodhd_calls into v_new_total;

  return v_new_total is not null;
end
$$;

revoke all on function public.reserve_hybrid_eodhd_calls(integer, integer)
  from public, anon, authenticated;
grant execute on function public.reserve_hybrid_eodhd_calls(integer, integer)
  to service_role;

create table if not exists public.news_sync_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null,
  finished_at timestamptz not null,
  ok boolean not null,
  auth_mode text,
  version text not null,
  provider text not null,
  inserted integer not null default 0,
  assessed integer not null default 0,
  rss_articles integer not null default 0,
  eodhd_calls integer not null default 0,
  warning_count integer not null default 0,
  error_message text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.news_sync_runs enable row level security;

drop policy if exists "authenticated_read_news_sync_runs"
  on public.news_sync_runs;
create policy "authenticated_read_news_sync_runs"
  on public.news_sync_runs
  for select
  to authenticated
  using (true);

grant select on table public.news_sync_runs to authenticated;
revoke insert, update, delete on table public.news_sync_runs
  from anon, authenticated;
grant select, insert, update, delete on table public.news_sync_runs
  to service_role;
grant usage, select on sequence public.news_sync_runs_id_seq
  to service_role;

create index if not exists idx_news_sync_runs_finished
  on public.news_sync_runs(finished_at desc);

create index if not exists idx_news_sync_runs_status
  on public.news_sync_runs(ok, finished_at desc);

comment on table public.hybrid_market_cache is
  'Serverseitiger Schlusskurscache für die kontingentsparende V29.2-Hybridbewertung.';
comment on table public.hybrid_api_usage is
  'UTC-Tageszähler für durch sync-news reservierte EODHD-Aufrufe.';
comment on table public.news_sync_runs is
  'Nachweis automatischer und manueller News-Sync-Läufe für die Dashboard-Statusanzeige.';
